
# The setup to load up the stack
setup: |
  # Setup LSST stack for {week}
  .  /software/lsstsw/stack/loadLSST.bash
  setup lsst_distrib -t {week}


templates:

  singleFrameDriver: >
    singleFrameDriver.py /datasets/DC2/repo --rerun {rerun} --batch-type slurm
    --mpiexec='-bind-to socket' --job {jobname} --cores 24 --time 900  --id visit={visit};

  makeSkyMap: >
    makeSkyMap.py /datasets/DC2/repo --rerun {rerun} --no-versions >& log_makeSkyMap_{weeknumber}

  coaddDriver:
    head_task: |
      #!/bin/bash -l
    multi: >-
      coaddDriver.py /datasets/DC2/repo --rerun {rerun}:{week}/coadd -c makeCoaddTempExp.doApplyUberCal=False
      -c assembleCoadd.doApplyUberCal=False --batch-type=slurm --mpiexec='-bind-to socket' --time 600 --cores 24
      --job coadd{filter}{tract} --id filter={filter} tract={tract} --selectId visit={visit};

  multiBandDriver:
    head_task: |
      #!/bin/bash -l
    multi: >-
      multiBandDriver.py /datasets/DC2/repo --rerun {week}/coadd:{week}/multi --batch-type=slurm --mpiexec='-bind-to socket'
      --job mt{tract}-{patch} --core 1 --time 45000 -c measureCoaddSources.propagateFlags.ccdName='detector'
      --id filter={filter_str} tract={tract} patch={patch_alt};

# Extra specs per task beyond the template
tasks_specs:
  empty

# Extnames for tasks
tasks_extname:
  makeSkyMap: '.sh'
  singleFrameDriver: '.sh'
  coaddDriver: '.sh'
  multiBandDriver: '.sh'

tasks_per_visit_tracts:
  - singleFrameDriver

tasks_per_tract_filter:
  - coaddDriver

tasks_per_tract_patch:
  - multiBandDriver

tasks_per_task:
  - makeSkyMap

tasks_to_execute_ordered:
  - singleFrameDriver
  - makeSkyMap
  - coaddDriver
  - multiBandDriver
